stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode -Dmaven.test.skip=false"
  DOCKER_HOST: "tcp://docker:2375/"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - ./mvnw $MAVEN_CLI_OPTS clean compile

test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-21
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""   # отключаем TLS для docker:dind
  script:
    - ./mvnw $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml