name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build (compile only)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Compile
        run: ./mvnw -B -U -DskipTests clean compile

      - name: Upload compiled classes (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compiled-classes
          path: target

  test:
    name: Tests (incl. Testcontainers Kafka)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run tests
        run: ./mvnw -B test

      - name: Publish JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: |
            target/surefire-reports/*.xml
            target/failsafe-reports/*.xml
